# Settings for the HPCC site
baseURL = "https://hpcc.ucr.edu"
relativeURLs = true
title = "HPCC"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
#pygmentsUseClasses = false
pygmentsCodeFences = false
pygmentsCodefencesGuessSyntax = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
#pygmentsStyle = "monokai"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
#[blackfriday]
#plainIDAnchors = true
#hrefTargetBlank = true
#angledQuotes = false
#latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

# Language configuration

[languages]
[languages.en]
title = "HPCC"
description = "Home of UCR's HPCC"
languageName ="English"
# Weight used for sorting.
#weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
#[outputs]
#section = ["HTML", "print"]

[params]
copyright = "The Docsy Authors"
privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
# version_menu = "Releases"

# server location time will be used to parse timestamps in markdown headers
# See this for locations https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# if not provided, UTC will be used
serverTimeLocation = "America/Los_Angeles"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
#version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
#url_latest_version = "https://example.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/ucr-hpcc/ucr-hpcc.github.io"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
# github_project_repo = "https://github.com/google/docsy"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Uncomment this if you have a newer GitHub repo with "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
# github_branch= "main"

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "d72aa9b2712488cc3"

# Enable Algolia DocSearch
# algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = true

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
# enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
# yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
# no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = true

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "Email Support"
	url = "mailto:support@hpcc.ucr.edu"
	icon = "fa fa-envelope"
        desc = "Please email your questions to us."
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/UCR_HPCC"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter for the latest updates."
[[params.links.user]]
	name = "Stack Overflow"
	url = "https://ucr-hpcc.slack.com/"
	icon = "fab fa-slack"
        desc = "For immediate help, users can also post questions here."
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
#	name = "GitHub"
#	url = "https://github.com/google/docsy"
#	icon = "fab fa-github"
#        desc = "Development takes place here!"
[[params.links.developer]]
#	name = "Slack"
#	url = "https://example.org/slack"
#	icon = "fab fa-slack"
#        desc = "Chat with other project developers"
[[params.links.developer]]
#	name = "Developer mailing list"
#	url = "https://example.org/mail"
#	icon = "fa fa-envelope"
#        desc = "Discuss development issues around the project"

###################
# Main Menu (top) #
###################

# About
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1
  pre = "<i class='fas fa-info-circle btn-primary'></i>"
  [[menu.main]]
    parent = "About"
    name = " Overview " # Keep whitespace to display item, bug?
    url = "/about/overview/"
    weight = 1
    [[menu.main]]
      parent = "About"
      name = " Introduction " # Keep whitespace to display item, bug?
      url = "/about/overview/introduction/"
      weight = 2
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "About"
      name = "Access" 
      url = "/about/overview/access/"
      weight = 3
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "About"
      name = "Activity Report"
      url = "/about/overview/activity/"
      weight = 4
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "About"
      name = "Rates"
      url = "/about/overview/rates/"
      weight = 5
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "About"
      name = "Contact"
      url = "/about/overview/contact/"
      weight = 7
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "About"
      name = "Acknowledgement"
      url = "/about/overview/acknowledgement/"
      weight = 8
      [menu.main.params]
        level = 2
  [[menu.main]]
    parent = "About"
    name = "Hardware"
    url = "/about/hardware/"
    weight = 10
    [[menu.main]]
      parent = "About"
      name = "Overview"
      url = "/about/hardware/overview"
      weight = 11
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "About"
      name = "Details"
      url = "/about/hardware/details"
      weight = 12
      [menu.main.params]
        level = 2
  [[menu.main]]
    parent = "About"
    name = "Software"
    url = "/about/software/"
    weight = 13
    [[menu.main]]
      parent = "About"
      name = "Installs"
      url = "/about/software/installs/"
      weight = 14
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "About"
      name = "Conda Packages"
      url = "/about/software/conda_packages/"
      weight = 14
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "About"
      name = "Modules"
      url = "/about/software/modules/"
      weight = 15
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "About"
      name = "System"
      url = "/about/software/system/"
      weight = 16
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "About"
      name = "Commercial"
      url = "/about/software/commercial"
      weight = 17
      [menu.main.params]
        level = 2

# News
[[menu.main]]
  name = "News"
  url = "/news"
  weight = 2
  pre = "<i class='fas fa-newspaper btn-primary'></i>"
  [[menu.main]]
    parent = "News"
    name = "Announcements"
    url = "/news/announce/"
    weight = 1
  [[menu.main]]
    parent = "News"
    name = "Alerts"
    url = "/news/alerts/"
    weight = 2
  [[menu.main]]
    parent = "News"
    name = "Upgrades"
    url = "/changes/"
    weight = 3

# Events
[[menu.main]]
  name = "Events"
  url = "/events"
  weight = 3
  pre = "<i class='fas fa-users btn-primary'></i>"
  [[menu.main]]
    parent = "Events"
    name = "Workshops"
    url = "/events/small/"
    weight = 1
  [[menu.main]]
    parent = "Events"
    name = "Related Events"
    url = "/events/related/"
    weight = 2

# Manuals
[[menu.main]]
  name = "Manuals"
  url = "/Manuals"
  weight = 4
  pre = "<i class='fas fa-book btn-primary'></i>"
  # HPC Linux Basics Sub-menu
  [[menu.main]]
    parent = "Manuals"
    name = " Access " # Keep whitespace to display item, bug?
    url = "/Manuals/access"
    weight = 1
    [[menu.main]]
      parent = "Manuals"
      name = "How to Get Account?"
      url = "/about/facility/access/"
      weight = 2
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Login"
      url = "/Manuals/access/login"
      weight = 3
      [menu.main.params]
        level = 2
  # HPC Linux Basics Sub-menu
  [[menu.main]]
    parent = "Manuals"
    name = "Linux Basics"
    url = "/manuals/linux_basics/"
    weight = 4
    [[menu.main]]
      parent = "Manuals"
      name = "Command Line Basics"
      url = "/Manuals/linux_basics/cmdline_basics"
      weight = 5
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "File Systems and Transfers"
      url = "/Manuals/linux_basics/filesystems"
      weight = 6
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Permissions and Ownership"
      url = "/Manuals/linux_basics/permissions"
      weight = 7
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Finding Things"
      url = "/Manuals/linux_basics/finding_things"
      weight = 8
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Text Editors"
      url = "/Manuals/linux_basics/Text"
      weight = 9
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Streams"
      url = "/Manuals/linux_basics/Streams"
      weight = 10
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Piping"
      url = "/Manuals/linux_basics/pipes"
      weight = 11
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Variables"
      url = "/Manuals/linux_basics/Variables"
      weight = 12
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Scripting"
      url = "/Manuals/linux_basics/Scripting"
      weight = 13
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Processe Management"
      url = "/Manuals/linux_basics/Processes"
      weight = 14
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Shell Bootcamp"
      url = "/Manuals/linux_basics/Shell"
      weight = 15
      [menu.main.params]
        level = 2
  # HPC Cluster Sub-menu
  [[menu.main]]
    parent = "Manuals"
    name = "HPC Cluster"
    url = "/Manuals/hpc_cluster/"
    weight = 17
    [[menu.main]]
      parent = "Manuals"
      name = "Introduction"
      url = "/Manuals/hpc_cluster/intro"
      weight = 18
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Getting Started"
      url = "/Manuals/hpc_cluster/start"
      weight = 19 
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Managing Jobs"
      url = "/Manuals/hpc_cluster/jobs"
      weight = 20
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Queue Policies"
      url = "/Manuals/hpc_cluster/Queue"
      weight = 21
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Package Management"
      url = "/Manuals/hpc_cluster/package_manage"
      weight = 22
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Selected Software"
      url = "/Manuals/hpc_cluster/selected_software"
      weight = 23
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Data Storage"
      url = "/Manuals/hpc_cluster/Storage"
      weight = 24
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Sharing Data"
      url = "/Manuals/hpc_cluster/sharing"
      weight = 25
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Data Security"
      url = "/Manuals/hpc_cluster/Security"
      weight = 26
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Communicating"
      url = "/Manuals/hpc_cluster/users"
      weight = 27
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Terminal IDEs"
      url = "/Manuals/hpc_cluster/terminalIDE"
      weight = 28
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Parallel Evaluations in R"
      url = "/Manuals/hpc_cluster/parallelR"
      weight = 29
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "SSH Keys"
      url = "/Manuals/hpc_cluster/sshkeys"
      weight = 30
      [menu.main.params]
        level = 2
    [[menu.main]]
      parent = "Manuals"
      name = "Visualization"
      url = "/Manuals/hpc_cluster/visual"
      weight = 31
      [menu.main.params]
        level = 2
  # HPC Cloud / AWS Sub-menu
  [[menu.main]]
    parent = "Manuals"
    name = "Cloud/External"
    url = "/manuals/ext_cloud/"
    weight = 31
    [[menu.main]]
      parent = "Manuals"
      name = "AWS"
      url = "/Manuals/ext_cloud/aws/"
      weight = 32
      [menu.main.params]
        level = 2

# Links
[[menu.main]]
  name = "Links"
  url = "/links/"
  pre = "<i class='fas fa-share-alt btn-primary'></i>"
  weight = 5
  [[menu.main]]
    name = "RED-UCR"
    url = "https://research.ucr.edu"
    parent = "Links"
    weight = 1
  [[menu.main]]
    name = "Data Science Center"
    url = "http://datascience.ucr.edu"
    parent = "Links"
    weight = 2
  [[menu.main]]
    name = "FIELDS Program"
    url = "http://bigdata.ucr.edu"
    parent = "Links"
    weight = 3
  [[menu.main]]
    name = "Institute of Integrative Genome Biology"
    url = "http://genomics.ucr.edu"
    parent = "Links"
    weight = 4

